name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install flask
        run: pip install flask
      - name: Install pytest
        run: pip install pytest
      - name: Run test suite
        run: pytest *.py

  deploy-to-impaas:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ImPaaS-Deploy
        uses: /impaas/impaas-deploy@v3
        with:
          app-name: wp624-counter
          deployment-token: ${{ secrets.IMPAAS_DEPLOY_TOKEN }}
          method: PLATFORM

